[project]
name = "cached-dilated-causal-convolutions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "amaranth==0.5.4",
    "amaranth-soc @ git+https://github.com/amaranth-lang/amaranth-soc@main",
    "fxpmath==0.4.8",
    "jupyter>=1.1.1",
    "kaleido>=1.3.0",
    "keras",
    "numpy",
    "plotly>=6.8.0",
    "pytest>=9.0.3",
    "qkeras==0.9.0",
    "scikit-learn==1.3.0",
    "seaborn==0.12.2",
    "sounddevice>=0.5.5",
    "tensorflow[and-cuda]==2.16.2",
    "zarr>=2.18.3",
]
