[project]
name = "cached-dilated-causal-convolutions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "amaranth==0.5.4",
    "fxpmath==0.4.8",
    "jupyter>=1.1.1",
    "keras==2.11.0",
    "numpy==1.25.2",
    "pytest>=9.0.3",
    "qkeras==0.9.0",
    "scikit-learn==1.3.0",
    "seaborn==0.12.2",
    "tensorflow[and-cuda]==2.11.0",
]
