SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES = ../../src/activation_cache.sv
TOPLEVEL = activation_cache
MODULE = activation_cache_tb

include $(shell cocotb-config --makefiles)/Makefile.sim
