SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES = ../../src/left_shift_buffer.sv
TOPLEVEL = left_shift_buffer
MODULE = left_shift_buffer_tb

include $(shell cocotb-config --makefiles)/Makefile.sim
